[package]
name = "super-prime-mover"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
edition = "2018"
license = "WTFPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
